### PR TITLE
Partially fixes #27 by supporting python 2.7+, removes requests dependancy.

### LINKED ISSUE #27: Python 2.6 and 3.2 broken
PR https://github.com/aclark4life/vanity/pull/23 broke Vanity for Python 2.6 and 3.2.

Python 2.6:
```
Traceback (most recent call last):
 File "vanity.py", line 24, in <module>
    from collections import deque, OrderedDict
ImportError: cannot import name OrderedDict
```

Python 3.2:
```
Traceback (most recent call last):
  File "vanity.py", line 38, in <module>
    import requests
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/requests-2.11.0-py3.2.egg/requests/__init__.py", line 64, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/requests-2.11.0-py3.2.egg/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

See https://travis-ci.org/hugovk/vanity/builds/154439793

These are on the PR https://github.com/aclark4life/vanity/pull/26 branch.

cc @mattjegan

### PR DESCRIPTION
**Pull request by mattjegan**
Managed to make the json parsing work without requiring the `requests` package. Keeps the project lightweight.

## Now requires py2.7+
As discussed in issue #27 `argparse` and `collections.OrderDict` are incompatible with py2.6 unless we add dependancies for the `argparse` and `ordereddict` packages.

### CODE REVIEW

**Comment by hugovk** [comment]
Looks good for all non-2.6:
https://travis-ci.org/hugovk/vanity/builds/154506446

If 2.6 is being ditched, please also remove it from .travis.yml:
https://github.com/aclark4life/vanity/blob/master/.travis.yml#L6

**Comment by mattjegan** [comment]
Should be good now 😄

**Comment by hugovk** [comment]
Python 2.6 is no longer supported so could be dropped, see https://github.com/aclark4life/vanity/issues/27#issuecomment-252412410.

@mattjegan Would you like to resolve conflicts in this PR?

**Comment by mattjegan** [comment]
Sure, @hugovk , if it's not urgent I should be able to patch it up tomorrow.

**Comment by mattjegan** [comment]
In summary, @aclark4life and @hugovk, this PR removes support for python 2.6 and 3.2 as discussed here and in #27. It also removes the dependancy on `requests` in favour of `urllib`

**Comment by hugovk** [comment]
Looks good!

I'm not too bothered either way, but if 3.2 is still working, should it be left in, and just 2.6 removed?

**Comment by mattjegan** [comment]
If we leave this PR as is, that is with `requests` removed, then I think we should be fine leaving 3.2 in. However, if we keep `requests` 3.2 fails, as seen in the Travis output for #32

**Comment by aclark4life** [comment]
Yeah I say get rid of ``3.2`` support, it's > 5 years old now I think.

**Comment by hugovk** [comment]
@mattjegan Merged, thanks!

**Pull request merged**
