### PR TITLE
Added badges

### PR DESCRIPTION
**Pull request by mattjegan**
* Enabled the badges in README
* Added new PyPi version badge from badge.fury.io as pypipins is no longer maintained/working
* No idea why my pypy tests fail, this is fresh from master.

### CODE REVIEW

**Comment by hugovk** [comment]
Does badge.fury.io have a downloads count badge?

Another option is https://shields.io/

PS you can add "[CI skip]" to prevent a documentation-only commit from building: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by hugovk** [comment]
OK, thank you for all the comments Coveralls... I've disabled it from commenting in future.

**Comment by hugovk** [comment]
@mattjegan Could also add in a Landscape badge.

**Comment by mattjegan** [comment]
@hugovk no worries, should be a few minutes.

**Comment by mattjegan** [comment]
@hugovk There seems to be one already included for landscape, it was just wasn't visible before this PR. I've also included one for downloads now.

**Comment by mattjegan** [comment]
@hugovk made versioning badge and coverage badges source from shields.io to keep consistancy

**Comment by hugovk** [comment]
Before consistency:
image

After, looks better:
image

Hmm, maybe 0 downloads/month isn't much to brag about...

Is it possible to remove that grey line on the left? I think it's a blockquote.

Could you switch the coverage one to point to the master branch rather than the travisci branch? (The coverage unknown is probably just some caching, as it's only just been turned on, so let's not worry about that.)

**Comment by mattjegan** [comment]
@hugovk How's that? I removed the downloads for the time being, perhaps this is related to the PyPI download count issue?

**Comment by hugovk** [comment]
Yeah, it could well be linked to the download issue.

**Pull request merged**
